//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRNApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public string ItemDecription { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> BatchCode { get; set; }
        public Nullable<int> Inventory { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    }
}
