//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRNApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public string ItemsDescription { get; set; }
        public int BatchCode { get; set; }
        public Nullable<int> Recived { get; set; }
        public Nullable<decimal> PriceInfo { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
